freq: 10.0
output_frame: odom_combined
sensor_timeout: 1.0
publish_tf: true
odom_used: true
imu_used: true
gps_used: true

# Change line below if visual odometry is available
vo_used: false

# Change line below if compass data is available (only applicable if gps is available)
imu_absolute: false
