analyzers:
  grizzly:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Grizzly Base
    analyzers:
      general:
        type: diagnostic_aggregator/GenericAnalyzer
        path: General
        remove_prefix: 'grizzly_node'
        timeout: 5.0
        expected: [
          'grizzly_node: General',
          'grizzly_node: Battery',
          'grizzly_node: User voltage supplies',
          'grizzly_node: Current consumption',
          'grizzly_node: Power consumption',
          'grizzly_node: Temperature' ]
      motors:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Motors
        remove_prefix: 'grizzly_node'
        timeout: 5.0
        expected: [
          'grizzly_node: Puma motor driver on: rear_left_wheel with CAN ID (2)',
          'grizzly_node: Puma motor driver on: rear_right_wheel with CAN ID (3)',
          'grizzly_node: Puma motor driver on: front_right_wheel with CAN ID (4)',
          'grizzly_node: Puma motor driver on: front_left_wheel with CAN ID (5)']
      sensors:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Sensor Topics
        remove_prefix: 'grizzly_node'
        timeout: 5.0
        expected: [
          'grizzly_node: /imu/data_raw topic status']
