analyzers:
  grizzly:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Grizzly T100
    find_and_remove_prefix: 'grizzly_base: '
    expected: ['grizzly_base: power_status','grizzly_base: system_status','grizzly_base: safety_status','grizzly_base: software_status']
    timeout: 5.0
